[package]
name = "TrackVault"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = "9.2.0"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jwt = "0.16.0"
gethostname = "0.5.0"
sysinfo = "0.33.1"
pnet = "0.35.0"
